vendor: Xerox
model: B8090
updated_at: '2026-04-20T18:49:22.113860+00:00'
codes:
  09-605-00:
    description: Fuser EOL
    severity: Critical
    component: fuser
    notes: ''
  07-545-00:
    description: Tray 2 empty
    severity: Low
    component: tray
    notes: ''
